import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '../components/homepage/footer/Footer'
import ResponsiveNav from "@/components/homepage/navbar/responsiveNav";
import { CartProvider } from "@/app/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
            <ResponsiveNav />
             {/* GLOBAL OFFSET FOR FIXED NAV */}
              <main className="pt-40 md:pt-44">
                {children}
              </main>
            <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
